Models/ErrorViewModel.cs
namespace mvc.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;

namespace mvc.Controllers{
    public class AuthController : Controller{
        public IActionResult Login(){
            return View();
        }
        
    }
}

Controllers/DashController.cs
using Microsoft.AspNetCore.Mvc;

namespace mvc.Controllers{
    public class DashController : Controller{
        public IActionResult Index(){
            return View();

        }
        
    }
}

Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;

namespace mvc.Controllers{
    public class ProductsController : Controller{
        public IActionResult Index(){
            return View();
        }

        
        
    }
}

Controllers/UsersController.cs
using Microsoft.AspNetCore.Mvc;

namespace mvc.Controllers{
    public class UsersController : Controller{
        public IActionResult Index(){
            return View();
        }
        public IActionResult Create(){
            return View();
        }

        public IActionResult Show(){
            return View();
        }

        public IActionResult Edit(){
            return View();
        }

        public IActionResult Update(){
            return View();
        }
        public IActionResult Eliminar(){
            return View();
        }
        
    }
}

Views/Dash/Index.cshtml
<h1 style="text-align: center; font-size: 50px;" class="mt-5">Bienvenidos a mi pagina</h1>
<br><br><br><br>
<center>
<div class="container mt-5 ">
<div class="row mt-5"">
        <div class="col-md-3">
            <button  style="background-color: bisque;" asp-controller="Users" asp-action="Index"> Gestion de productos</button>
        </div>
        <div class="col-md-3">
            <button style="background-color: bisque; " >Registrate</button>
        </div>
        <div class="col-md-3">
            <button style="background-color: bisque;" >Gestion de usuarios</button>
        </div>

</div>
</div>

Views/Products/Index.cshtml
<div class="container">
    <div style="display: flex;  ">
         <a class="nav-link " asp-area="" asp-controller="Dash" asp-action="Index" style="margin: 20px;">Inicio</a>
        <p style="margin: 20px;">Gestion de usuarios</p>
    </div>
    <div>
        
        <a asp-controller="Users" asp-action="Create"><button class="btn btn-primary"  >Crear Nuevo  Producto</button></a>
    </div>
    <div class="row mt-5">
        
    <table class="table table-dark" >
    <thead>
        <tr>
            <th>Imagen</th>
            <th>Nombre</th>
            <th>Precio</th>
            <th>Cantidad</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        
        <tr>
            <td><img src="" alt=""></td>
            <td>Papa</td>
            <td>$5000</td>
            <td>9</td>
            <td>
            <a asp-controller="Users" asp-action="Eliminar"><button class="btn btn-danger">eliminar</button></a>
            <a  asp-controller="Users" asp-action="Edit"> <button class="btn btn-warning">editar</button></a>
            <a  asp-controller="Users" asp-action="Show"> <button class="btn btn-info"> detalles</button></a>
            </td>
        </tr>
    </tbody>
</table>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/mvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Dash" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index" >Usuarios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Productos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">Registrate</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Users/Create.cshtml
<div style="display: flex;  ">
         <a class="nav-link " asp-area="" asp-controller="Dash" asp-action="Index" style="margin: 20px;">Inicio</a>
        <p style="margin: 20px;">Gestion de usuarios</p>
    </div>
<div class="row  mt-5">

    <center>
<div>
 <div class="col-md-7">
    <form>
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Nombres</label>
    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    
  </div>
   <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Apellidos</label>
    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    
  </div>
   <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Correo</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    
  </div>
   <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">genero</label>
    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    
  </div>
   <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Edad</label>
    <input type="number" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    
  </div>
  
  <center>
  <a asp-area="" asp-controller="Users" asp-action="Index" ><button type="submit" class="btn btn-primary">Crear</button></a>
  </center>
</form>
 </div>
 </div>
    </center>
</div>

Views/Users/Edit.cshtml
  <div style="display: flex;  ">
         <a class="nav-link " asp-area="" asp-controller="Dash" asp-action="Index" style="margin: 20px;">Inicio</a>
        <p style="margin: 20px;">Gestion de usuarios</p>
    </div>

<div class="row">
    <div class="row  mt-5">

    <center>
<div>
 <div class="col-md-7">
    <form>
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Nombres</label>
    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Pedro">
    
  </div>
   <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Apellidos</label>
    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Gonzales">
    
  </div>
   <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Correo</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Pedro@pedro">
    
  </div>
   <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">genero</label>
    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Hombre">
    
  </div>
   <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Edad</label>
    <input type="number" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="22">
    
  </div>
  
</form>

  <center>
  <a asp-area="" asp-controller="Users" asp-action="Update" ><button type="submit" class="btn btn-warning">Editar</button></a>
  </center>
 </div>
 </div>
    </center>
</div>

Views/Users/Eliminar.cshtml
  <div style="display: flex;  ">
         <a class="nav-link " asp-area="" asp-controller="Dash" asp-action="Index" style="margin: 20px;">Inicio</a>
        <p style="margin: 20px;">Gestion de usuarios</p>
    </div>

<div class="row">
    <div class="col-md-10" style="border: 3px solid black; height: 300px; background-color: rgb(131, 192, 131);" >
        <br><br><br><br>
        <h4 style="text-align: center;">Se ha eliminado el usuario con éxito ✔️</h4><br><br><br>
        <center>
        <a  asp-controller="Users" asp-action="Index"> <button class="btn btn-primary">Ver listado de usuarios</button></a>
        </center>
    </div>
</div>

Views/Users/Index.cshtml
<div class="container">
    <div style="display: flex;  ">
         <a class="nav-link " asp-area="" asp-controller="Dash" asp-action="Index" style="margin: 20px;">Inicio</a>
        <p style="margin: 20px;">Gestion de usuarios</p>
    </div>
    <div>
        
        <a asp-controller="Users" asp-action="Create"><button class="btn btn-primary"  >Crear Nuevo  Usuario</button></a>
    </div>
    <div class="row mt-5">
        
    <table class="table table-dark" >
    <thead>
        <tr>
            <th>Nombres</th>
            <th>Apellidos</th>
            <th>Correo</th>
            <th>Género</th>
            <th>Edad</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        
        <tr>
            <td>Juan</td>
            <td>Pérez</td>
            <td>juan@example.com</td>
            <td>Masculino</td>
            <td>30</td>
            <td>
            <a asp-controller="Users" asp-action="Eliminar"><button class="btn btn-danger">eliminar</button></a>
            <a  asp-controller="Users" asp-action="Edit"> <button class="btn btn-warning">editar</button></a>
            <a  asp-controller="Users" asp-action="Show"> <button class="btn btn-info"> detalles</button></a>
            </td>
        </tr>
    </tbody>
</table>
    </div>
</div>

Views/Users/Show.cshtml
<div style="display: flex;  ">
        <a class="nav-link " asp-area="" asp-controller="Dash" asp-action="Index" style="margin: 20px;">Inicio</a>
        <p style="margin: 20px;">Gestion de usuarios</p>
</div>
<center>
<div class="row mt-5" >
    <div class="col-md-12" style="border: 4px solid black; display: flex;" >
        <div class="col-md-5">
            <p>nombres :  Juan david </p>
            <p>apellido : usuga Zapata</p>
            <p>edad :  20 </p>
        </div>
        <div class="col-md-5">
            <p>correo: deklan.com</p>
            <p>genero: m</p>
        </div>
</div>
</center>
<div class="mt-5">
    <center>
    
    <a asp-controller="Users" asp-action="Index" ><button class="btn btn-primary">Ver lista de usuarios</button></a>
    </center>
</div>
</div>

Views/Users/Update.cshtml
  <div style="display: flex;  ">
         <a class="nav-link " asp-area="" asp-controller="Dash" asp-action="Index" style="margin: 20px;">Inicio</a>
        <p style="margin: 20px;">Gestion de usuarios</p>
    </div>

<div class="row">
    <div class="col-md-10" style="border: 3px solid black; height: 300px; background-color: rgb(131, 192, 131);" >
        <br><br><br><br>
        <h4 style="text-align: center;">Se ha actualizado con exito ✔️</h4><br><br><br>
        <center>
        <a  asp-controller="Users" asp-action="Index"> <button class="btn btn-primary">Ver listado de usuarios</button></a>
        </center>
    </div>
</div>